theme: jekyll-theme-minimal
title: "Zinc Engine"
description: "Zinc Engine is a mod for Friday Night Funkin', including a full engine rework, replays, and more."
show_downloads: true
replace_index_with: "https://cors-thing.puyo.workers.dev/master/"
logo: "https://github.com/ZincDev/Zinc-Engine/raw/master/ZincEngineLogo.png"
url: "https://ZincDev.github.io/Zinc-Engine/"
